services:
  - type: web
    name: youtube-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0